languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "燎原斗"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
#  logo = "img/logo.png"
  copyright = "© { year } <span class='inline-block'>A-Do</span> All Rights Reserved</span>."

[params.author]
  name = "燎原斗"
  image = "img/bear-cat-logo.png"
  headline = "胸无大志也是一种智慧"
  bio = "真的就这么晚，急不来"
  links = [
    { envelope = "yydy215@gmail.com" },
    { bars = "/about" },
  ]